version: '3.8'

services:

  keycloak:
    build: ./keycloak
    container_name: keycloak
    command: ["start", "--optimized"]
    environment:
      - KC_EXTERNAL_ADDR=host.docker.internal
      - KC_BIND_ADDR=keycloak
      - KC_BIND_PORT=7800
      - KC_INITIAL_HOSTS=keycloak[7800],host.docker.internal[7801]
    env_file:
      - ./keycloak/keycloak.env
    ports:
      - 8080:8080
      - 7800:7800
    networks:
      - net1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  keycloak-02:
    build: ./keycloak
    container_name: keycloak-02
    command: "start --optimized"
    environment:
      - KC_EXTERNAL_ADDR=host.docker.internal
      - KC_BIND_ADDR=keycloak-02
      - KC_BIND_PORT=7801
      - KC_INITIAL_HOSTS=host.docker.internal[7800],keycloak-02[7801]
    env_file:
      - ./keycloak/keycloak.env
    ports:
      - 8081:8080
      - 7801:7801
    networks:
      - net2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  busybox:
    image: busybox
    container_name: busybox
    command: "tail -f /dev/null"
    networks:
      - net3
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  net1:
  net2:
  net3:
